spin_manifest_version = 2

[application]
name = "social-timer"
version = "0.1.8"
authors = ["Markus Klink <justjoheinz@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "social-timer"

[component.social-timer]
source = "target/wasm32-wasip1/release/social_timer.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.social-timer.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=social_timer cargo build --lib --target wasm32-wasip1 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "style/**/*.scss", "Cargo.toml"]

[[trigger.http]]
route = "/pkg/..."
component = "social-timer-pkg"

[component.social-timer-pkg]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "target/site/pkg", destination = "/" }]

[[trigger.http]]
route = "/static/..."
component = "assets"

[component.assets]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
